In [1]:
import pandas as pd
import folium

!pip install folium

In [2]:
trip_data = pd.read_csv("final_dataset.csv")

In [3]:
trip_data

,Date Time,Status,Speed(Km/h),Latitude,Longitude,Reference,Mileage,Geo_Fencing,route,speed_diff,harsh_breaking,harsh_acceleration,Trip,over_speeding
0,2023-01-01 00:54:36,Ignition On,0,30.22050,71.47538,"0.00 Km From Central College Multan, Opp Unive...",12,"{'place_id': 204232145, 'licence': 'Data © Ope...",1,0.0,0,0,1,0
1,2023-01-01 00:54:41,Normal,0,30.22050,71.47538,"0.00 Km From Central College Multan, Opp Unive...",12,"{'place_id': 204232145, 'licence': 'Data © Ope...",1,0.0,0,0,1,0
2,2023-01-01 00:54:46,Normal,0,30.22050,71.47538,"0.00 Km From Central College Multan, Opp Unive...",12,"{'place_id': 204232145, 'licence': 'Data © Ope...",1,0.0,0,0,1,0
3,2023-01-01 00:54:51,Normal,0,30.22050,71.47538,"0.00 Km From Central College Multan, Opp Unive...",12,"{'place_id': 204232145, 'licence': 'Data © Ope...",1,0.0,0,0,1,0
4,2023-01-01 00:54:56,Normal,0,30.22050,71.47538,"0.00 Km From Central College Multan, Opp Unive...",12,"{'place_id': 204232145, 'licence': 'Data © Ope...",1,0.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39487,2023-02-14 09:27:38,Normal,6,24.85648,67.00739,"0.00 Km From CPLC Parking, Court St, Ali Dina ...",1136,"{'place_id': 218567200, 'licence': 'Data © Ope...",0,0.0,0,0,127,0
39488,2023-02-14 09:27:40,Normal,7,24.85650,67.00739,"0.00 Km From CPLC Parking, Court St, Ali Dina ...",1136,"{'place_id': 218567200, 'licence': 'Data © Ope...",0,1.0,0,0,127,0
39489,2023-02-14 09:27:44,Passenger SeatBelt Close,0,24.85652,67.00742,"0.00 Km From CPLC Parking, Court St, Ali Dina ...",1136,"{'place_id': 218567200, 'licence': 'Data © Ope...",0,-7.0,0,0,127,0
39490,2023-02-14 09:27:46,Driver SeatBelt Close,0,24.85652,67.00742,"0.00 Km From CPLC Parking, Court St, Ali Dina ...",1136,"{'place_id': 218567200, 'licence': 'Data © Ope...",0,0.0,0,0,127,0
39491,2023-02-14 09:27:51,Ignition Off,0,24.85652,67.00742,"0.00 Km From CPLC Parking, Court St, Ali Dina ...",1136,"{'place_id': 218567200, 'licence': 'Data © Ope...",0,0.0,0,0,127,0

In [4]:
trip_data["Date Time"] = pd.to_datetime(trip_data["Date Time"])

In [5]:
trip_data = trip_data.sort_values("Date Time", ignore_index = True)

In [6]:
trip_group = trip_data.groupby("Trip")

In [7]:
trip = trip_group.get_group(106)

In [8]:
trip

,Date Time,Status,Speed(Km/h),Latitude,Longitude,Reference,Mileage,Geo_Fencing,route,speed_diff,harsh_breaking,harsh_acceleration,Trip,over_speeding
27065,2023-02-08 09:53:47,Ignition On,0,28.92011,70.62502,"0.00 Km From Zahir Pir Service Area-South, Dr....",311,"{'place_id': 249117431, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
27066,2023-02-08 09:53:52,Normal,0,28.92011,70.62502,"0.00 Km From Zahir Pir Service Area-South, Dr....",311,"{'place_id': 249117431, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
27067,2023-02-08 09:53:57,Normal,0,28.92011,70.62502,"0.00 Km From Zahir Pir Service Area-South, Dr....",311,"{'place_id': 249117431, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
27068,2023-02-08 09:54:02,Normal,0,28.92011,70.62502,"0.00 Km From Zahir Pir Service Area-South, Dr....",311,"{'place_id': 249117431, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
27069,2023-02-08 09:54:07,Normal,0,28.92011,70.62502,"0.00 Km From Zahir Pir Service Area-South, Dr....",311,"{'place_id': 249117431, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28926,2023-02-08 11:56:43,Normal,0,27.65900,68.93644,"1.00 Km From Arror Filling Station, Saleh Pat ...",536,"{'place_id': 246342258, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
28927,2023-02-08 11:56:48,Normal,0,27.65900,68.93644,"1.00 Km From Arror Filling Station, Saleh Pat ...",536,"{'place_id': 246342258, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
28928,2023-02-08 11:56:54,Normal,0,27.65900,68.93644,"1.00 Km From Arror Filling Station, Saleh Pat ...",536,"{'place_id': 246342258, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
28929,2023-02-08 11:56:59,Normal,0,27.65900,68.93644,"1.00 Km From Arror Filling Station, Saleh Pat ...",536,"{'place_id': 246342258, 'licence': 'Data © Ope...",1,0.0,0,0,106,0
28930,2023-02-08 11:57:03,Ignition Off,0,27.65900,68.93644,"1.00 Km From Arror Filling Station, Saleh Pat ...",536,"{'place_id': 246342258, 'licence': 'Data © Ope...",1,0.0,0,0,106,0

In [9]:
trip_route = trip[["Latitude","Longitude"]]
trip_route.head()

       Latitude  Longitude
27065  28.92011   70.62502
27066  28.92011   70.62502
27067  28.92011   70.62502
27068  28.92011   70.62502
27069  28.92011   70.62502

In [11]:
#trip_route = trip[["Latitude","Longitude"]]
Latitude = trip_route["Latitude"].values
Longitude = trip_route["Longitude"].values

In [12]:
Latitude

array([28.92011, 28.92011, 28.92011, ..., 27.659  , 27.659  , 27.659  ])

In [13]:
Longitude

array([70.62502, 70.62502, 70.62502, ..., 68.93644, 68.93644, 68.93644])

In [14]:
my_Map = folium.Map()
my_Map.save("project.html")

In [15]:
my_Map = folium.Map([Latitude[0],Longitude[0]])
my_Map.save("project.html")

In [17]:
my_Map = folium.Map([24.9026737,67.1118726], zoom_start = 14 )
my_Map.save("project.html")

In [18]:
trip_route.values

array([[28.92011, 70.62502],
       [28.92011, 70.62502],
       [28.92011, 70.62502],
       ...,
       [27.659  , 68.93644],
       [27.659  , 68.93644],
       [27.659  , 68.93644]])

In [19]:
my_Map = folium.Map([Latitude[0],Longitude[0]])

folium.PolyLine(trip_route.values, color = "blue", weight=5, opacity = 1).add_to(my_Map)

my_Map.save("project.html")

In [21]:
from folium.plugins import AntPath

In [22]:
# AntPath Line (location 1 to location 2)

<b> Danial </b>

##<img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>

<a href="https://techmazone.com"> Techma ZOne Web</a>

In [25]:
my_Map = folium.Map([Latitude[0],Longitude[0]])

AntPath(trip_route.values, delay = 1000, dash_array = [15,30], color = "black", 
        pulse_color = "yellow", weight = 5, opacity = 0.9, tooltip = "<b>Home to Office</b>",
       popup = folium.Popup("""
       <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
       <center><a href="https://techmazone.com">Techma Zone Website</a></center>
       """
       )).add_to(my_Map)

my_Map.save("project.html")

In [ ]:
# Pin location

In [26]:
my_Map = folium.Map([Latitude[0],Longitude[0]])

AntPath(trip_route.values, delay = 1000, dash_array = [15,30], color = "black", 
        pulse_color = "yellow", weight = 5, opacity = 0.9, tooltip = "<b>Home to Office</b>",
       popup = folium.Popup("""
       <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
       <center><a href="https://techmazone.com">Techma Zone Website</a></center>
       """
       )).add_to(my_Map)

folium.Marker([Latitude[0],Longitude[0]], popup="Home",
             icon = folium.Icon(color = "green", icon = "glyphicon glyphicon-heart")).add_to(my_Map)

folium.Marker([Latitude[-1],Longitude[-1]], popup="""
            <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
           <center><a href="https://techmazone.com">Techma Zone Website</a></center>
            """,
             icon = folium.Icon(color = "blue", icon = "glyphicon glyphicon-briefcase")).add_to(my_Map)


my_Map.save("project.html")

In [27]:
# Over-Speeding

over_speeding_location = trip.loc[trip["over_speeding"] == 1,["Latitude","Longitude"]]
over_speeding_location.head()

       Latitude  Longitude
27197  28.88708   70.58680
27217  28.87344   70.55904
27218  28.87314   70.55843
27219  28.87268   70.55751
27220  28.87222   70.55656

In [28]:
over_speeding_location.shape

(544, 2)

In [30]:
over_speeding_location.head(30)

       Latitude  Longitude
27197  28.88708   70.58680
27217  28.87344   70.55904
27218  28.87314   70.55843
27219  28.87268   70.55751
27220  28.87222   70.55656
27221  28.87176   70.55561
27222  28.87130   70.55466
27223  28.87083   70.55370
27224  28.87037   70.55276
27225  28.86992   70.55183
27226  28.86946   70.55092
27227  28.86902   70.55000
27228  28.86856   70.54907
27245  28.85780   70.52715
27246  28.85735   70.52624
27269  28.84317   70.49853
27270  28.84259   70.49770
27271  28.84199   70.49687
27272  28.84136   70.49606
27273  28.84072   70.49526
27295  28.82233   70.47347
27296  28.82170   70.47272
27297  28.82106   70.47196
27298  28.82040   70.47120
27299  28.81975   70.47044
27300  28.81910   70.46967
27301  28.81845   70.46889
27302  28.81781   70.46813
27303  28.81717   70.46737
27304  28.81652   70.46661

In [31]:
points = over_speeding_location.index
points

Int64Index([27197, 27217, 27218, 27219, 27220, 27221, 27222, 27223, 27224,
            27225,
            ...
            28841, 28842, 28847, 28860, 28861, 28862, 28863, 28864, 28865,
            28902],
           dtype='int64', length=544)

In [ ]:
#distances = [points[i+1] - points[i] for i in range(len(points)-1)]

In [ ]:
#distances[:10]

In [35]:
distances = pd.Series(points).diff().dropna().astype(int).values.tolist()

In [36]:
enumerate(distances)

In [38]:
list(enumerate(distances))[:15]

[(0, 20),
 (1, 1),
 (2, 1),
 (3, 1),
 (4, 1),
 (5, 1),
 (6, 1),
 (7, 1),
 (8, 1),
 (9, 1),
 (10, 1),
 (11, 1),
 (12, 17),
 (13, 1),
 (14, 23)]

In [39]:
final_lst = []
lst = []

for ind,i in list(enumerate(distances)):
    if i == 1:
        lst.append(ind)
    else:
        final_lst.append(lst)
        lst = []

In [41]:
final_lst[:3]

[[], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [13]]

In [42]:
final_lst = [i for i in final_lst if len(i) > 5]

In [44]:
final_lst[:5]

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [20, 21, 22, 23, 24, 25, 26, 27, 28],
 [46, 47, 48, 49, 50, 51, 52],
 [58, 59, 60, 61, 62, 63, 64],
 [77, 78, 79, 80, 81, 82]]

In [45]:
final_lst[0]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [50]:
len(final_lst)

22

In [49]:
ovs = over_speeding_location.iloc[final_lst[0]]
ovs

       Latitude  Longitude
27217  28.87344   70.55904
27218  28.87314   70.55843
27219  28.87268   70.55751
27220  28.87222   70.55656
27221  28.87176   70.55561
27222  28.87130   70.55466
27223  28.87083   70.55370
27224  28.87037   70.55276
27225  28.86992   70.55183
27226  28.86946   70.55092
27227  28.86902   70.55000

In [51]:
my_Map = folium.Map([Latitude[0],Longitude[0]])

AntPath(trip_route.values, delay = 1000, dash_array = [15,30], color = "black", 
        pulse_color = "yellow", weight = 5, opacity = 0.9, tooltip = "<b>Home to Office</b>",
       popup = folium.Popup("""
       <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
       <center><a href="https://techmazone.com">Techma Zone Website</a></center>
       """
       )).add_to(my_Map)

folium.Marker([Latitude[0],Longitude[0]], popup="Home",
             icon = folium.Icon(color = "green", icon = "glyphicon glyphicon-home")).add_to(my_Map)

folium.Marker([Latitude[-1],Longitude[-1]], popup="""
            <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
           <center><a href="https://techmazone.com">Techma Zone Website</a></center>
            """,
             icon = folium.Icon(color = "blue", icon = "glyphicon glyphicon-briefcase")).add_to(my_Map)

#overspeeding
AntPath(ovs.values, delay = 300, dash_array = [15,30], color = "red", 
        pulse_color = "yellow", weight = 7, opacity = 1, tooltip = "<b>Home to Office</b>",
       popup = folium.Popup("""
       <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
       <center><a href="https://techmazone.com">Techma Zone Website</a></center>
       """
       )).add_to(my_Map)


my_Map.save("project.html")

In [52]:
my_Map = folium.Map([Latitude[0],Longitude[0]])

AntPath(trip_route.values, delay = 1000, dash_array = [15,30], color = "black", 
        pulse_color = "yellow", weight = 5, opacity = 0.9, tooltip = "<b>Home to Office</b>",
       popup = folium.Popup("""
       <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
       <center><a href="https://techmazone.com">Techma Zone Website</a></center>
       """
       )).add_to(my_Map)

folium.Marker([Latitude[0],Longitude[0]], popup="Home",
             icon = folium.Icon(color = "green", icon = "glyphicon glyphicon-home")).add_to(my_Map)

folium.Marker([Latitude[-1],Longitude[-1]], popup="""
            <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
           <center><a href="https://techmazone.com">Techma Zone Website</a></center>
            """,
             icon = folium.Icon(color = "blue", icon = "glyphicon glyphicon-briefcase")).add_to(my_Map)

#overspeeding

for i in range(len(final_lst)):
    ovs = over_speeding_location.iloc[final_lst[i]]
    AntPath(ovs.values, delay = 300, dash_array = [15,30], color = "red", 
            pulse_color = "yellow", weight = 7, opacity = 1, tooltip = "<b>Home to Office</b>",
           popup = folium.Popup("""
           <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
           <center><a href="https://techmazone.com">Techma Zone Website</a></center>
           """
           )).add_to(my_Map)


my_Map.save("project.html")

In [54]:
my_Map = folium.Map([Latitude[0],Longitude[0]])

layer1 = folium.GeoJson(
    data = (open("pakistan.geojson","r").read()),
    name="Pakistan")

layer1.add_to(my_Map)

AntPath(trip_route.values, delay = 1000, dash_array = [15,30], color = "black", 
        pulse_color = "yellow", weight = 5, opacity = 0.9, tooltip = "<b>Home to Office</b>",
       popup = folium.Popup("""
       <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
       <center><a href="https://techmazone.com">Techma Zone Website</a></center>
       """
       )).add_to(my_Map)

folium.Marker([Latitude[0],Longitude[0]], popup="Home",
             icon = folium.Icon(color = "green", icon = "glyphicon glyphicon-home")).add_to(my_Map)

folium.Marker([Latitude[-1],Longitude[-1]], popup="""
            <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
           <center><a href="https://techmazone.com">Techma Zone Website</a></center>
            """,
             icon = folium.Icon(color = "blue", icon = "glyphicon glyphicon-briefcase")).add_to(my_Map)

#overspeeding

for i in range(len(final_lst)):
    ovs = over_speeding_location.iloc[final_lst[i]]
    AntPath(ovs.values, delay = 300, dash_array = [15,30], color = "red", 
            pulse_color = "yellow", weight = 7, opacity = 1, tooltip = "<b>Home to Office</b>",
           popup = folium.Popup("""
           <img src="https://techmazone.com/assets/images/logo-v3.png" width="150"/>
           <center><a href="https://techmazone.com">Techma Zone Website</a></center>
           """
           )).add_to(my_Map)

    
# add tile layers
folium.TileLayer('openstreetmap').add_to(my_Map)
folium.TileLayer('stamenterrain', attr="stamenterrain").add_to(my_Map)
folium.TileLayer('stamenwatercolor', attr="stamenwatercolor").add_to(my_Map)

folium.TileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', 
 name='CartoDB.DarkMatter', attr="CartoDB.DarkMatter").add_to(my_Map)
folium.TileLayer('https://tile.openstreetmap.bzh/br/{z}/{x}/{y}.png', 
 name='OpenStreetMap.BZH', attr="OpenStreetMap.BZH").add_to(my_Map)

folium.TileLayer('https://tileserver.memomaps.de/tilegen/{z}/{x}/{y}.png', 
 name='My Tile', attr="OPNVKarte").add_to(my_Map)


folium.LayerControl().add_to(my_Map)

my_Map.save("project.html")